### ISSUE TITLE
Fix Flying Electric Robot Platform Collision.

### ISSUE THREAD

**Issue by Jasuutu** [Alriightyman/Megaman#4]
From what I have discovered about the flying electric robot and how we should be able to get Magaman to stick to the platform, everything code wise should be correct. It looks like the problem is with the collision itself. Not sure if it's worth taking a look at it now or after you finish converting everything to sprites but at some point we need to take a look at fixing the collision on this guy.

**Comment by Jasuutu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix Collision of Flying Electric Robot](https://trello.com/c/spHfbH03/2-fix-collision-of-flying-electric-robot)

**Comment by Alriightyman** [comment]
Fixed by making the Player.cs script run before the CharacterController2D.cs script.
